http:
  routers:
    proxmox:
      rule: "Host(`proxmox.home.phuchoang.sbs`)"
      entryPoints:
        - websecure
      service: proxmox
      tls:
        certResolver: letsencrypt

  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://10.69.1.1:8006"
        serversTransport: insecureTransport

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true # For self-signed SSL certificates
