name: ollama
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - "OLLAMA_BASE_URL=http://ollama:11434"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${APPDATA}/open-webui:/app/backend/data
    ports:
      - "8081:8080"

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      OLLAMA_KEEP_ALIVE: 1h
      OLLAMA_FLASH_ATTENTION: 1
      OLLAMA_KV_CACHE_TYPE: q4_0
    volumes:
      - ${APPDATA}/ollama:/root/.ollama
    ports:
      - "11434:11434"
